### PR TITLE
Add support for AVR-DA and AVR-DB series

### PR DESCRIPTION
**Pull request by MCUdude**
Initial support for AVR-DA and AVR-DB series using [DxCore](https://github.com/SpenceKonde/DxCore).
The only thing I'm not sure I got right is the core name. I've used `dxcore` instead of `DxCore`.
After this is hopefully merged, I'll start working on the fuses script.

@valeros does everything look alright?

(#11 related)

### CODE REVIEW

**Comment by MCUdude** [comment]
@ivankravets or @valeros, is there any chance of this repo being prioritized in the near future? There are more things to be done if/when this PR gets merged, like dynamic fuses for AVR-DA/DB's and perhaps bootloader support. There is also #17, which is pretty much mandatory if these microcontrollers should work with Avrdude

**Comment by valeros** [comment]
Thanks for the PR! I've uploaded the DxCore package and restarted the CI build, but it looks like there is a problem with [AVR128DB*](https://github.com/platformio/platform-atmelmegaavr/pull/18/checks?check_run_id=1779731775#step:5:2003) boards. Is there any chance that we're using an outdated toolchain?

**Comment by MCUdude** [comment]
> Thanks for the PR! I've uploaded the DxCore package and restarted the CI build, but it looks like there is a problem with AVR128DB* boards. Is there any chance that we're using an outdated toolchain?

That is very much the case I think. The AVR-DB's are pretty new, and need a toolchain refresh. How do you usually do this? Do you use [Atmel pack](http://packs.download.atmel.com) patches? I know @SpenceKonde has solved this by compiling his own toolchain for DxCore that he distributes with the boards manager installation. In [this](http://drazzy.com/package_drazzy.com_index.json) boards manager URL he refers to this "custom" toolchain as "7.3.0-atmel3.6.1-azduino3".

**Comment by valeros** [comment]
We usually use the same packages as Arduino. Can we safely switch to the DxCore toolchains also for the `MegaCoreX` and `megatinycore`?

**Comment by MCUdude** [comment]
> We usually use the same packages as Arduino. Can we safely switch to the DxCore toolchains also for the MegaCoreX and megatinycore?

@SpenceKonde would have to answer this. All I know is that this version is very fresh and only bundled with DxCore v1.3.0 which is the latest release. Or we can wait with the AVR-DB parts until they are supported in the Arduino toolchain. I think this is the best perhaps.

**Comment by MCUdude** [comment]
The latest official Arduino toolchain is pretty much out of date when it comes to AVR-DA and AVR-DB. Only a handful of targets are supported (AVR128DA*), and there's a lot of bugs too. As you can see in the Atmel packs description, a lot of bugs have been fixed recently, but the Arduino toolchain still uses AVR-Dx pack 1.0.27 and not the latest, 1.6.76.

Maybe @SpenceKonde's version is the way to go after all? This PR isn't worth much without a proper toolchain... 😢

**Comment by valeros** [comment]
There is no need to hurry, I propose to postpone support for DxCore to the next release.

**Comment by MCUdude** [comment]
> There is no need to hurry, I propose to postpone support for DxCore to the next release.

That is OK. I just hope you're available to continue working on this when a new toolchain is available!

**Comment by MCUdude** [comment]
Oh! If you look in #19, @brunob45 has created a python patch file that gets the latest Atmel pack in order to support AVR-DB. Maybe this is something worth looking more into?

**Comment by valeros** [comment]
Yeah, I've seen that PR, but I don't think it's a good idea to introduce additional extra complexity even only for CI builds when it's possible to simply use proper toolchains.

**Comment by MCUdude** [comment]
> Yeah, I've seen that PR, but I don't think it's a good idea to introduce additional extra complexity even only for CI builds when it's possible to simply use proper toolchains.

That's understandable. I'll do what I can to get the official Arduino toolchain to support AVR-DB's. Meanwhile, we can just wait with this PR so you can do a new release of this repo.

BTW you should ta a look at this. I think it applies to this core too.
https://github.com/platformio/platform-atmelavr/issues/232
Either something is wrong with the version handling, or I and just dumb 😄

**Comment by btribley** [comment]
@SpenceKonde just released DxCore 1.3.1 . I would love to use PlatformIO with that core. Looking just at this thread it looks like the answer is, "not yet." Is that true?

**Comment by SpenceKonde** [comment]
You don't even need goddamned python to grab latest ATPacks if you are building the toolchain, I do it with wget when I build the toolchain. 
I think there were two issues that led to my not doing full toolchain builds, and instead doing what I did with Azduino3* were:
1. There are few things I enjoy less than setting up build toolchains. One of those is setting up cross-compilation tool chains in order to build the executables for platforms other than x64 linux. And I would have to set that up for 5 platforms (mac, win, x86 linux, and both arms). Okay, I ain't gonna do that even if I thought I had the background and experience. Which I don't. So I was like f this noise, I have clean binaries that work, neatly gathered in the correct file paths in an archive with "arduino7" in the filename ;-)  
2. More concerning was the fact that there appeared to be problems with even just x64 linux! In the time since then I've figured out what the issue is: The linker scripts you get out of the build process currently are NFG. I don't know what they should be, but I know that what they are is no good. Ih fact, that this is a problem dates back to I think around arduino7. I have a core to write, so again, said "f that noise, I have linker scripts that work fine"

So I build my toolchain pack by: 
Running the toolchain build process with latest atpacks (including the wget for atpack autofetch - which arduino turned up their nose at citing license concerns, which makes my BS alarm blare). That generates an x64 linux package  and then I delete all files that are executables or shared libraries for x64 linux from it. 
Then I extract the 6 arduino7 packages, copy those files over them, and recompress with azduino names, and then push them to my public S3 bucket for distribution. 

You are welcome to use my toolchain package - there's a working package for all 6 platforms the official IDE ones support - just one requirement: Rehost the packages somewhere. Like I said, they're hosted on S3 right now, and while I don't need to worry about the cost of bandwidth from arduino people installing third party cores, I do not want to sleep-walk into the situation of suddenly have a larger monthly bill than I want to help people who use an IDE other than the one I use (I already give my time for free developing these cores; I'd rather the cores just be a time sink, not a money sink as well) - but with DxCore and megaTinyCore alone, I aint even close to worrying about it..

* (Azduino is combination of Dr Azzy, my longtime online alias, and the __duino convention; I've got the URL, whenever I actually have time to start making the site exist)

**Comment by btribley** [comment]
@brunob45 and @MCUdude I see some evidence of at least the AVR128DA28 working. That's what I am targeting. Is there a guide for trying this out on PlatformIO? I'm experienced in other development and know my way around tools, just not as a low-level toolchain or core guy. It would be cool to get @SpenceKonde 's DxCore into PlatformIO the way it is right now so that it can be selected as a board. From what he wrote the toolchain is there and can be freely used.  At any rate I appreciate the effort being made to get these chips to the point where PlatformIO can be used to develop with the Arduino framework.

**Comment by MCUdude** [comment]
@valeros it seems like @SpenceKonde's toolchain for the AVR DA and DB series works well for on all platforms, Mac, Linux, and Windows. Maybe it's time to use this version with PlatformIO as well?

His latest toolchain patch also supports the tinyAVR-2 series and the up and coming AVR DD series.

You can find the toolchain download links here:
https://github.com/SpenceKonde/ReleaseScripts/blob/889aadc7b771aa2bb70d9519d43888d5a290f6aa/package_drazzy.com_index.json#L2561-L2605

As for the weird versioning, here's a snippet from the latest commit. I think the reason why the windows version is azduino4b and not 4a is that the Windows 4a version didn't have the right folder structure.

> (megaTinyCore)
"name": "2.3.1: No code changes, repack windows toolchain to resolve directory structure issue.<br/> 2.3.0: Initial 2-series release. No good on Windows, use 2.3.1.<br/> Version 2.2.9 is the stable version, with no 2-series support."

**Comment by SpenceKonde** [comment]
That is correct. I'm still getting the automation for the toolchain hacky toolchain update procedure down (they are not straight rebuilds - the pre-compiled .a files and related stuff is generated on the one platform I know how to do that on (which I don't have a test system for and can't actually *use* directly), and then used to upgrade the packages for all the platforms).,

Version 4 for unix-like OS's was missing the files under lib/ - that is, the new device-specs, so 4a was released with that repackaged, and the same windows package. Then I discovered that the windows package which I thought I had tested had an extra layer of folders (I'd selected the previous version to install in board manager...), and so that was repackaged, and released as 4b (and in 4b, the unix-like packages are the same as 4a)  

Generally once my toolchains have been released for a week or so without a re-release they can be trusted; the problems are never subtle - it's a complete failure to build anything because I copied files to the wrong place or missed some of the files. The actual compiler executables are the ones from Arduino7 - I don't know how to build the whole thing from scratch

**Comment by MCUdude** [comment]
> Generally once my toolchains have been released for a week or so without a re-release, they can be trusted; the problems are never subtle - it's a complete failure to build anything because I copied files to the wrong place or missed some of the files. The actual compiler executables are the ones from Arduino7 - I don't know how to build the whole thing from scratch

@valeros this should be good enough, right? If not, I'll guess it's easy enough to roll back to the previous toolchain version. I'm 100% we'll get feedback immediately if things aren't working the way they should.

**Comment by btribley** [comment]
This is great news. If you want I can test it as I am still in the final stages of the project for which I used the AVR128DA28 and I have a follow-on project using that chip as well. Will it support debugging? Arduino is the first platform I have used since I graduated in 1976 that has no debugger and that really, really sucks. Arduino IDE 2.0 supports debugging only if the core developer spends time to set it up despite debugging being built into the chip hardware. Solid code is predicated on stepping through everything important, can't tell how many latent bugs I have found watching my "working" code execute...

**Comment by btribley** [comment]
BTW because of lack of support for AVR128DA28 I uninstalled PlatformIO and went with Arduino IDE 1.8.13 using VS Code for the editor with the Microsoft Arduino plugin. IMHO if it worked PlatformIO looks to be a superior solution, but it couldn't work for my situation without a core.

**Comment by btribley** [comment]
@MCUdude I got my hopes up. Do you think a release will come soon? Thanks in advance for all the work required to pull it off.

**Comment by MCUdude** [comment]
> @MCUdude I got my hopes up. Do you think a release will come soon? Thanks in advance for all the work required to pull it off.

This is not up to me. The toolchain needs to be updated before this PR gets merged and a new release can be published. This is something @valeros  has to do, and sadly I don't know when or if it will happen.

**Comment by fiveangle** [comment]
It's looking pretty clear that Arduino isn't come to save us anytime soon.

It's a shame because these are of the few MCUs of this class that are readily available. By the time Arduino gets onboard, the supply chain woes will be behind us and nobody will really need this near as badly as we do now.

**Comment by SpenceKonde** [comment]
It *IS* too bad, as I've been offering platformio an updated toolchain packages for ages - my only condition is that they host it someplace other than my Amazon S3 bucket (I get charged based on bandwidth for everything except the x64 linux package, which I host on github because 95+% of the traffic comes from the github actions CI, but I don't want to push my luck by hosting everything there)

**Comment by btribley** [comment]
@SpenceKonde Do you have a rough idea of how much bandwidth would be required to host it? I am toying with it because I want a quality, no-thinking implementation of Arduino with a debugger using the AVR-Dx chips and your core is really good. I only wish they would come out with the D variants with low pin count. Still using PIC and their awful excuse for a tool, MPLAB, for my low pin count projects,....

**Comment by fiveangle** [comment]
Would it be viable to use one of the free-for-OSS CDNs ? https://www.keycdn.com/blog/free-cdns

**Comment by btribley** [comment]
It seems like it would. Most don't have restrictions. https://www.keycdn.com/open-source-cdn is apparently seeking open source developers who need hosting for their libraries. Given the range of entities using these CDNs certainly DxCore would qualify.

**Comment by MCUdude** [comment]
Closing this since #19 has been merged

**Pull request closed without merging**
